networks:
  main:
    name: docker-compose-local

services:
  postgres-db:
    container_name: postgres-db
    image: "public.ecr.aws/docker/library/postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    env_file:
      - ./container_config/postgres.env
    networks:
      main:
        aliases:
          - postgres-db
  mysql-db:
    container_name: mysql-db
    image: "public.ecr.aws/docker/library/mysql:${MYSQL_VERSION}"
    ports:
      - "3306:3306"
    env_file:
      - ./container_config/mysql.env
    networks:
      main:
        aliases:
          - mysql-db
  rabbitmq:
    container_name: rabbitmq
    image: "public.ecr.aws/docker/library/rabbitmq:${RABBITMQ_VERSION}"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./container_config/rabbitmq.env
    networks:
      main:
        aliases:
          - rabbitmq